### ISSUE TITLE
Prompt format to test open-source models

### ISSUE THREAD

**Issue by joslefaure** [longvideobench/LongVideoBench#4]
Thanks for releasing this dataset. I am wondering how you prompt and process the outputs of open-source models such as VideoChat2 and LLaVa. 
Do you include all the options in the prompt and ask the model to choose one of them or do you just ask it the question and match the model's output with the most similar of the list of options?

Thanks

**Comment by teowu** [comment]
Hi,

We are using an MCQ prompt for them, as follows:
```
[Question]
A. XXX
B. XXX
C. XXX
D. XXX
Please answer with the letter for the correct option. # or other similar prompts
```
